ENABLE:
  - JAVASCRIPT
  - JSON
  - YAML
  - MARKDOWN
  - GITHUB_ACTIONS

DISABLE:
  - SPELL

FILTER_REGEX_EXCLUDE: |
  (node_modules|dist|build|coverage|playwright-report|allure-report|allure-results)

APPLY_FIXES: none

VALIDATE_ALL_CODEBASE: false
