name: 🚀 Cypress Cucumber CI Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🚀 Start Application
        run: |
          npx live-server --port=8080 &
        shell: bash

      - name: ⏳ Wait for Application
        run: |
          npx wait-on http://127.0.0.1:8080

      - name: 🧪 Run Cypress Cucumber Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: 📸 Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: 🎥 Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
